version: '3'

services:
  mysql:
    container_name: cashforce
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=cashforce_v3
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"