version: '3.7'

services:
  mysql:
    container_name: cashforce
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=cashforce_v3
    volumes:
      - /var/db/startuphry/mysql:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/conf.d/settings.cnf
      - ./conf/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - backend
  client:
    build:
      context: ./client
      target: 'develop-stage'
    ports:
      - '8080:8080'
    command: "npm start"
    depends_on:
      - server
  server:
    links:
      - mysql
    depends_on:
      - mysql
    build:
      context: ./server
      target: 'develop-stage'
    ports:
      - '5000:5000'
    command: "npm start"
    networks:
      - backend

networks:
  backend:
    driver: 'bridge'